version: '3.9'
# образ для дебагинга
# https://habr.com/ru/articles/712670/
#  Здесь репа для конфига дебагера
#  https://gist.github.com/CViniciusSDias/c785b82e4f724d3737b43dfbe4ff8819

services:
    nginx:
      image: nginx:1.25.2-alpine
#      container_name: nginx
      ports:
        - 8080:80
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./src:/var/www/html
        - ./logs/nginx:/var/log/nginx/
      depends_on:
        php:
          condition: service_started
        mysql:
          condition: service_healthy
    php:
#      container_name: php
      build:
        context: .
        dockerfile: php/php.dockerfile
      working_dir: /var/www/php
      volumes:
        - ./src:/var/www/html
        - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
#        - ./logs/php/xdebug.log:/var/log/xdebug.log
      env_file:
        - ./.env.dev
      depends_on:
        mysql:
          condition: service_healthy
    mysql:
#      container_name: mysql
      image: mysql:5.7.34
      platform: linux/x86_64 # -- for Intel architecture
      #platform: linux/amd64 # -- for ARM (M1) architecture
      volumes:
        - mysql:/var/lib/mysql
      restart: always
      ports:
        - 3306:3306
      env_file:
        - ./.env.dev
      healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$DB_USER --password=$$DB_PASSWORD
        interval: 5s
        retries: 10

volumes:
  mysql:
    external: true
    name: mysql
